import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const liveResources = [
  // OPERATIONAL (17 total)
  { title: "Book Fair Administrator Operational Guide", slug: "book-fair-administrator-operational-guide", description: "Your complete guide for running a successful Catholic school book fair.", thumbnail: "/images/thumb-guide-catholic.png", fileUrl: "/documents/6972c6f5a779558d8d96668a_in-person-guide-catholic-1-22-26.pdf", category: "Operational", audience: "Catholic In Person", resourceType: "PDF", order: 1, featured: true },
  { title: "Parish Book Fair Administrator Operational Guide", slug: "parish-book-fair-administrator-operational-guide", description: "Your complete guide for running a successful parish in-person book fair.", thumbnail: "/images/thumb-guide-catholic.png", fileUrl: "/documents/in-person-guide-parish.pdf", category: "Operational", audience: "Parish In Person", resourceType: "PDF", order: 2, featured: false },
  { title: "Virtual Book Fair Operational Guide", slug: "virtual-book-fair-operational-guide", description: "Guide for running a virtual book fair.", thumbnail: "/images/thumb-guide-virtual.png", fileUrl: "/documents/697955719f97f8f497a88f4a_guide-vbf-1-27.pdf", category: "Operational", audience: "Catholic In Person", resourceType: "PDF", order: 3, featured: false },
  { title: "Digital Catalog", slug: "digital-catalog", description: "Browse the full digital catalog for your virtual book fair.", thumbnail: "/images/one-page-cat-v-thumb.png", fileUrl: "https://ignatius-book-fair.s3.us-east-2.amazonaws.com/ibf-digital-catalog-2-12-25.pdf", category: "Operational", audience: "Catholic In Person", resourceType: "PDF", order: 3.5, featured: false, parentGuide: "virtual-book-fair-operational-guide" },
  { title: "2025 Parent Letter", slug: "2025-parent-letter", description: "A letter to send to parents about your upcoming book fair.", thumbnail: "/images/in-person-pr-ltr-thumb.png", fileUrl: "/documents/68f7f856d30d6e5fee245e21_IBF-2025-parent-letter.pdf", category: "Operational", audience: "Catholic In Person", resourceType: "PDF", order: 4, featured: false },
  { title: "About Ave Dollars", slug: "about-ave-dollars", description: "Information about how Ave Dollars work.", thumbnail: "/images/about-ave-dollars-thumb.png", fileUrl: "/documents/6831f8b40468baa8c44158b9_about-ave-dollars.pdf", category: "Operational", audience: "Catholic In Person", resourceType: "PDF", order: 5, featured: false },
  { title: "POS Device Instructions", slug: "pos-device-instructions", description: "Instructions for setting up and using your POS device.", thumbnail: "/images/tip-sheet-thumb.png", fileUrl: "/documents/68e160d40ef1f7d8bd735326_ibf-pos-instructions.pdf", category: "Operational", audience: "Catholic In Person", resourceType: "PDF", order: 6, featured: true, parentGuide: "book-fair-administrator-operational-guide" },
  { title: "Social Media Guide", slug: "social-media-guide", description: "Copy, paste & post! A comprehensive guide for your book fair social media kit.", thumbnail: "/images/social-media-v-thumb.png", fileUrl: "/documents/68a71619ba01b9c8793e2691_IBF-social-media-tips.pdf", category: "Operational", audience: "Catholic In Person", resourceType: "PDF", order: 7, featured: false },
  { title: "Catholic School Planning Checklist", slug: "catholic-school-planning-checklist", description: "Planning checklist for Catholic school book fairs.", thumbnail: "/images/tip-sheet-thumb.png", fileUrl: "/documents/68d5b032234dec8cdc70b78c_ibf-planning-checklist-cath-schools.pdf", category: "Operational", audience: "Catholic In Person", resourceType: "PDF", order: 8, featured: false },
  { title: "Student Wishlist", slug: "student-wishlist", description: "Wishlist forms for students to share with their families.", thumbnail: "/images/student-wishlist-10-24-thumb.png", fileUrl: "https://ignatius-book-fair.s3.us-east-2.amazonaws.com/student-wishlist-1-25.pdf", category: "Operational", audience: "Catholic In Person", resourceType: "PDF", order: 9, featured: false },
  { title: "Teacher Wishlist", slug: "teacher-wishlist", description: "Wishlist forms for teachers.", thumbnail: "/images/teacher-bookfair-sighlist-thumb.png", fileUrl: "https://ignatius-book-fair.s3.us-east-2.amazonaws.com/teacher-bookfair-wishlist.pdf", category: "Operational", audience: "Catholic In Person", resourceType: "PDF", order: 10, featured: false },
  { title: "Virtual Student Wishlist", slug: "virtual-student-wishlist", description: "Virtual wishlist for students.", thumbnail: "/images/student-wishlist-10-24-thumb.png", fileUrl: "https://ignatius-book-fair.s3.us-east-2.amazonaws.com/Virtual+Student+Wish+List+Order+Form.pdf", category: "Operational", audience: "Catholic In Person", resourceType: "PDF", order: 11, featured: false },
  { title: "Category Signs", slug: "category-signs", description: "Signs to organize books by category at your fair.", thumbnail: "/images/category-signs.png", fileUrl: "https://ignatius-book-fair.s3.us-east-2.amazonaws.com/table-category-signs.pdf", category: "Operational", audience: "Catholic In Person", resourceType: "PDF", order: 12, featured: false },
  { title: "Pulpit Announcement", slug: "pulpit-announcement", description: "A script for announcing your book fair at Mass.", thumbnail: "/images/pr-thumb.png", fileUrl: "/documents/68979b7dfc136e7dc910063a_pulpit-announcement-6-28.pdf", category: "Operational", audience: "Catholic In Person", resourceType: "PDF", order: 13, featured: false },
  { title: "Last Copy Tags (ink saver)", slug: "last-copy-tags", description: "Tags for marking last copies of books.", thumbnail: "/images/thumb-lastcopy-inksaver.png", fileUrl: "https://ignatius-book-fair.s3.us-east-2.amazonaws.com/last-copy-less-color.pdf", category: "Operational", audience: "Catholic In Person", resourceType: "PDF", order: 14, featured: false },
  { title: "Coloring Sheet 1", slug: "coloring-sheet-1", description: "A fun coloring sheet for kids.", thumbnail: "/images/color-1-thumb.png", fileUrl: "https://ignatius-book-fair.s3.us-east-2.amazonaws.com/ColoringSheet01.pdf", category: "Operational", audience: "Catholic In Person", resourceType: "PDF", order: 15, featured: false, parentGuide: "book-fair-administrator-operational-guide" },
  { title: "Coloring Sheet 2", slug: "coloring-sheet-2", description: "A fun coloring sheet for kids.", thumbnail: "/images/color-2-thumb.png", fileUrl: "https://ignatius-book-fair.s3.us-east-2.amazonaws.com/ColoringSheet02.pdf", category: "Operational", audience: "Catholic In Person", resourceType: "PDF", order: 16, featured: false, parentGuide: "book-fair-administrator-operational-guide" },
  { title: "Coloring Sheet 3", slug: "coloring-sheet-3", description: "A fun coloring sheet for kids.", thumbnail: "/images/color-3-thumb.png", fileUrl: "https://ignatius-book-fair.s3.us-east-2.amazonaws.com/ColoringSheet03.pdf", category: "Operational", audience: "Catholic In Person", resourceType: "PDF", order: 17, featured: false, parentGuide: "book-fair-administrator-operational-guide" },

  // ADVERTISING (24 total)
  { title: "Lent Flyer - 2026", slug: "lent-flyer-2026", description: "Promotional flyer for Lent 2026 book fairs.", thumbnail: "/images/lent-flyer-thumb.png", fileUrl: "/documents/6978f960f0653915c0117b43_ibf-lent-2026.pdf", category: "Advertising", audience: "Catholic In Person", resourceType: "PDF", order: 22, featured: true },
  { title: "Back-to-School Flyer", slug: "back-to-school-flyer", description: "Promotional flyer for back-to-school book fairs.", thumbnail: "/images/thumb-back-to-school.png", fileUrl: "/documents/689e00d9478acdaee417f668_ibf-back-to-school-25.pdf", category: "Advertising", audience: "Catholic In Person", resourceType: "PDF", order: 23, featured: false },
  { title: "Table Signs", slug: "table-signs", description: "Signs for displaying at your book fair tables.", thumbnail: "/images/category-signs.png", fileUrl: "/documents/68e84ae6671c98f0a0843c57_ibf-table-signs.pdf", category: "Advertising", audience: "Catholic In Person", resourceType: "PDF", order: 24, featured: false },
  { title: "Toys and Trinkets", slug: "toys-and-trinkets", description: "Information about toys and trinkets at the book fair.", thumbnail: "/images/thumb-toys-trinkets.png", fileUrl: "/documents/696d166482c96b816aaae67f_ibf-toys-trinkets.pdf", category: "Advertising", audience: "Catholic In Person", resourceType: "PDF", order: 25, featured: false },
  { title: "Advent & Christmas Flyer, 2025", slug: "advent-christmas-flyer-2025", description: "Promotional flyer for Advent and Christmas 2025.", thumbnail: "/images/thumb-advent.png", fileUrl: "/documents/6913f79c51bf766c8ed7ff20_ibf-advent-christmas-2025-flyer.pdf", category: "Advertising", audience: "Catholic In Person", resourceType: "PDF", order: 26, featured: false },
  { title: "Fall Flyer - 2025", slug: "fall-flyer-2025", description: "Promotional flyer for Fall 2025 book fairs.", thumbnail: "/images/thumb-fall.png", fileUrl: "/documents/68fba800de20269d33805373_10-24_FallFlyer_V2.pdf", category: "Advertising", audience: "Catholic In Person", resourceType: "PDF", order: 27, featured: false },
  { title: "Fillable Backpack Flyer 1", slug: "fillable-backpack-flyer-1", description: "Customizable backpack flyer for your book fair.", thumbnail: "/images/thumb-fillable-backpack-1.png", fileUrl: "https://ignatius-book-fair.s3.us-east-2.amazonaws.com/Print_Backpack_Flyer.pdf", category: "Advertising", audience: "Catholic In Person", resourceType: "PDF", order: 28, featured: false },
  { title: "Fillable Backpack Flyer 2", slug: "fillable-backpack-flyer-2", description: "Customizable one-page catalog flyer.", thumbnail: "/images/thumb-fillable-backpack-2.png", fileUrl: "https://ignatius-book-fair.s3.us-east-2.amazonaws.com/03-02_IBF_OnePageCatalog_V1.pdf", category: "Advertising", audience: "Catholic In Person", resourceType: "PDF", order: 29, featured: false, parentGuide: "book-fair-administrator-operational-guide" },
  { title: "Fillable Social Media Post 2", slug: "fillable-social-media-post-2", description: "Customizable social media post template.", thumbnail: "/images/digital-package-v-thumb.png", fileUrl: "https://ignatius-book-fair.s3.us-east-2.amazonaws.com/DigitalPackage-SocialPost-01_v2.pdf", category: "Advertising", audience: "Catholic In Person", resourceType: "PDF", order: 30, featured: false },
  { title: "Fillable Social Media Story", slug: "fillable-social-media-story", description: "Customizable social media story template.", thumbnail: "/images/social-media-v-thumb.png", fileUrl: "https://ignatius-book-fair.s3.us-east-2.amazonaws.com/DigitalPackage-SocialStory-02_V2.pdf", category: "Advertising", audience: "Catholic In Person", resourceType: "PDF", order: 31, featured: false },
  { title: "Principal Parent Letter - In Person", slug: "principal-parent-letter-in-person", description: "Letter from principal to parents for in-person fairs.", thumbnail: "/images/principal-letter-thumb.png", fileUrl: "https://ignatius-book-fair.s3.us-east-2.amazonaws.com/In-Person-Principal-Letter-To-Parents.pdf", category: "Advertising", audience: "Catholic In Person", resourceType: "PDF", order: 32, featured: false },
  { title: "Principal Parent Letter - Virtual", slug: "principal-parent-letter-virtual", description: "Letter from principal to parents for virtual fairs.", thumbnail: "/images/virtual-pr-ltr-thumb.png", fileUrl: "https://ignatius-book-fair.s3.us-east-2.amazonaws.com/Virtual-Book-Fair-Principal-Letter-To-Parents.pdf", category: "Advertising", audience: "Catholic In Person", resourceType: "PDF", order: 33, featured: false, parentGuide: "virtual-book-fair-operational-guide" },
  { title: "Reading Challenge Campaign", slug: "reading-challenge-campaign", description: "Materials for running a reading challenge campaign.", thumbnail: "/images/thumb-reading-challenge.png", fileUrl: "https://ignatius-book-fair.s3.us-east-2.amazonaws.com/Reading-Challenge-Campaign.pdf", category: "Advertising", audience: "Catholic In Person", resourceType: "PDF", order: 34, featured: false, parentGuide: "book-fair-administrator-operational-guide" },
  { title: "Virtual Backpack Flyer 2", slug: "virtual-backpack-flyer-2", description: "One-page catalog for virtual book fairs.", thumbnail: "/images/one-page-cat-v-thumb.png", fileUrl: "/documents/660f4b5e3b099f4f6988322f_one-page-catalog-virtual.pdf", category: "Advertising", audience: "Catholic In Person", resourceType: "PDF", order: 35, featured: false, parentGuide: "virtual-book-fair-operational-guide" },
  { title: "Bookfair Sneak Peek", slug: "bookfair-sneak-peek", description: "Preview of books available at your book fair.", thumbnail: "/images/thumb-bookfair-sneak-peek.png", fileUrl: "/documents/690e49fc2d7126889ee7cb3c_IBF-Catholic-Sneak-Peek-Online.pdf", category: "Advertising", audience: "Catholic In Person", resourceType: "PDF", order: 36, featured: true, parentGuide: "book-fair-administrator-operational-guide" },
  { title: "You Caption It - Social Media Post", slug: "you-caption-it-social-media-post", description: "Social media post template - add your own caption.", thumbnail: "/images/social-media-v-thumb.png", fileUrl: "https://ignatius-book-fair.s3.us-east-2.amazonaws.com/DigitalPackage-SocialPost-03.jpg", category: "Advertising", audience: "Catholic In Person", resourceType: "Image", order: 37, featured: false, parentGuide: "book-fair-administrator-operational-guide" },
  { title: "You Caption It: Social Media Story", slug: "you-caption-it-social-media-story", description: "Social media story template - add your own caption.", thumbnail: "/images/social-media-v-thumb.png", fileUrl: "https://ignatius-book-fair.s3.us-east-2.amazonaws.com/DigitalPackage-SocialStory-04.jpg", category: "Advertising", audience: "Catholic In Person", resourceType: "Image", order: 38, featured: false },
  { title: "Parent Letter - Personalized School Link", slug: "parent-letter-personalized-school-link", description: "A personalized parent letter with your school's book fair link.", thumbnail: "/images/in-person-pr-ltr-thumb.png", fileUrl: "/documents/68f7f856d30d6e5fee245e21_IBF-2025-parent-letter.pdf", category: "Advertising", audience: "Catholic In Person", resourceType: "PDF", order: 38.1, featured: false },
  { title: "Virtual Fillable Social Media Post 1", slug: "virtual-fillable-social-media-post-1", description: "Customizable virtual social media post template.", thumbnail: "/images/digital-package-v-thumb.png", fileUrl: "/documents/digital-package-virtual.pdf", category: "Advertising", audience: "Catholic In Person", resourceType: "PDF", order: 38.2, featured: false, parentGuide: "virtual-book-fair-operational-guide" },
  { title: "Virtual Fillable Yellow Print Flyer", slug: "virtual-fillable-yellow-print-flyer", description: "Customizable yellow print flyer for virtual book fairs.", thumbnail: "/images/flyer-virtual-thumb.png", fileUrl: "/documents/flyer-virtual.pdf", category: "Advertising", audience: "Catholic In Person", resourceType: "PDF", order: 38.3, featured: false, parentGuide: "virtual-book-fair-operational-guide" },
  { title: "Virtual You Caption It: Social Media or Print Ad 2", slug: "virtual-you-caption-it-2", description: "Virtual social media or print ad template - add your own caption.", thumbnail: "/images/social-media-virtual.jpg", fileUrl: "/documents/social-media-virtual.jpg", category: "Advertising", audience: "Catholic In Person", resourceType: "Image", order: 38.4, featured: false, parentGuide: "virtual-book-fair-operational-guide" },
  { title: "What Makes an Ignatius Book Fair Special", slug: "what-makes-an-ignatius-book-fair-special", description: "Video about what makes Ignatius Book Fairs unique.", thumbnail: "/images/ibf-video-thumb.png", category: "Advertising", audience: "Catholic In Person", resourceType: "Video", embedCode: '<wistia-player media-id="pl16fxhzoe"></wistia-player>', order: 38.5, featured: false },
  { title: "You Caption It: Social Media or Print Ad 1", slug: "you-caption-it-social-media-print-ad-1", description: "Social media or print ad template - add your own caption.", thumbnail: "/images/social-media-v-thumb.png", fileUrl: "https://ignatius-book-fair.s3.us-east-2.amazonaws.com/DigitalPackage-08.jpg", category: "Advertising", audience: "Catholic In Person", resourceType: "Image", order: 38.6, featured: false, parentGuide: "book-fair-administrator-operational-guide" },
  { title: "You Caption It: Social Media or Print Ad 2", slug: "you-caption-it-social-media-print-ad-2", description: "Social media or print ad template - add your own caption.", thumbnail: "/images/social-media-v-thumb.png", fileUrl: "https://ignatius-book-fair.s3.us-east-2.amazonaws.com/DigitalPackage-09.jpg", category: "Advertising", audience: "Catholic In Person", resourceType: "Image", order: 38.7, featured: false },

  // TUTORIALS (7 Loom videos)
  { title: "Creating a Parent Account", slug: "creating-a-parent-account", description: "Video tutorial on creating a parent account.", thumbnail: "/images/ibf-video-thumb.png", category: "Tutorials", audience: "Catholic In Person", resourceType: "Video", embedCode: '<iframe src="https://www.loom.com/embed/69e61b1a5f4d4dfda0db8e11848303de" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="width: 100%; height: 100%;"></iframe>', order: 39, featured: false, parentGuide: "book-fair-administrator-operational-guide" },
  { title: "Creating your Admin Account", slug: "creating-your-admin-account", description: "Video tutorial on creating an admin account.", thumbnail: "/images/ibf-video-thumb.png", category: "Tutorials", audience: "Catholic In Person", resourceType: "Video", embedCode: '<iframe src="https://www.loom.com/embed/13970b1c86994c5184ecb5beb09278f4" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="width: 100%; height: 100%;"></iframe>', order: 40, featured: true },
  { title: "Features for Teachers", slug: "features-for-teachers", description: "Video tutorial on teacher features.", thumbnail: "/images/ibf-video-thumb.png", category: "Tutorials", audience: "Catholic In Person", resourceType: "Video", embedCode: '<iframe src="https://www.loom.com/embed/29cc79e431a349489dc7a37f2b82d22e" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="width: 100%; height: 100%;"></iframe>', order: 41, featured: false },
  { title: "How to Invite a Teacher to a Classroom", slug: "how-to-invite-a-teacher-to-a-classroom", description: "Video tutorial on inviting teachers.", thumbnail: "/images/ibf-video-thumb.png", category: "Tutorials", audience: "Catholic In Person", resourceType: "Video", embedCode: '<iframe src="https://www.loom.com/embed/9c41ba28d86347aba36c33895b52459a" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="width: 100%; height: 100%;"></iframe>', order: 42, featured: false },
  { title: "How to Share School Link with Families", slug: "how-to-share-school-link-with-families", description: "Video tutorial on sharing your school link.", thumbnail: "/images/ibf-video-thumb.png", category: "Tutorials", audience: "Catholic In Person", resourceType: "Video", embedCode: '<iframe src="https://www.loom.com/embed/cc08f11c1fb54c4b84295cd82d559050" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="width: 100%; height: 100%;"></iframe>', order: 43, featured: false },
  { title: "How to Use Your Ave Dollars", slug: "how-to-use-your-ave-dollars", description: "Video tutorial on using Ave Dollars.", thumbnail: "/images/ibf-video-thumb.png", category: "Tutorials", audience: "Catholic In Person", resourceType: "Video", embedCode: '<iframe src="https://www.loom.com/embed/0caf52bfffa94bdc8b796e8f82d20a8c" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="width: 100%; height: 100%;"></iframe>', order: 44, featured: false },
  { title: "How your Orders Benefit your School", slug: "how-your-orders-benefit-your-school", description: "Video tutorial on school benefits from orders.", thumbnail: "/images/ibf-video-thumb.png", category: "Tutorials", audience: "Catholic In Person", resourceType: "Video", embedCode: '<iframe src="https://www.loom.com/embed/6a43bd855ffc4a6da1cb05312e339963" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="width: 100%; height: 100%;"></iframe>', order: 45, featured: false },

  // POS TUTORIALS (8 YouTube videos + 1 PDF)
  { title: "POS: Bar Code Not Working? How to Search for a Book by Title", slug: "pos-barcode-not-working", description: "Troubleshooting barcode issues on POS.", thumbnail: "https://img.youtube.com/vi/MvkGtaXUg28/hqdefault.jpg", category: "Tutorials", audience: "Catholic In Person", resourceType: "Video", embedCode: '<iframe src="https://www.youtube.com/embed/MvkGtaXUg28" frameborder="0" allowfullscreen></iframe>', order: 46, featured: false },
  { title: "POS: Connecting an External Credit Card Reader to Your Payment Device", slug: "pos-connecting-external-credit-card-reader", description: "How to connect external card reader to POS.", thumbnail: "https://img.youtube.com/vi/WoDM0oj8X-U/hqdefault.jpg", category: "Tutorials", audience: "Catholic In Person", resourceType: "Video", embedCode: '<iframe src="https://www.youtube.com/embed/WoDM0oj8X-U" frameborder="0" allowfullscreen></iframe>', order: 47, featured: false },
  { title: "POS: How to Go Back, Get to the Home Screen, and Clear Open Screens", slug: "pos-navigation", description: "POS navigation and screen clearing.", thumbnail: "https://img.youtube.com/vi/lbYpsWl_p0M/hqdefault.jpg", category: "Tutorials", audience: "Catholic In Person", resourceType: "Video", embedCode: '<iframe src="https://www.youtube.com/embed/lbYpsWl_p0M" frameborder="0" allowfullscreen></iframe>', order: 48, featured: false },
  { title: "POS: How to Keep Your Ignatius Book Fair App Up to Date", slug: "pos-keep-app-up-to-date", description: "Keeping your POS app updated.", thumbnail: "https://img.youtube.com/vi/1tFi8jy6JzE/hqdefault.jpg", category: "Tutorials", audience: "Catholic In Person", resourceType: "Video", embedCode: '<iframe src="https://www.youtube.com/embed/1tFi8jy6JzE" frameborder="0" allowfullscreen></iframe>', order: 49, featured: false },
  { title: "POS: How to Log Out if Another School is Logged In", slug: "pos-logout-other-school", description: "Logging out another school from POS.", thumbnail: "https://img.youtube.com/vi/GoE7skcrJt8/hqdefault.jpg", category: "Tutorials", audience: "Catholic In Person", resourceType: "Video", embedCode: '<iframe src="https://www.youtube.com/embed/GoE7skcrJt8" frameborder="0" allowfullscreen></iframe>', order: 50, featured: false },
  { title: "POS: How to Process a Return", slug: "pos-process-return", description: "Processing returns on the POS system.", thumbnail: "https://img.youtube.com/vi/k7KcO3pX7Z4/hqdefault.jpg", category: "Tutorials", audience: "Catholic In Person", resourceType: "Video", embedCode: '<iframe src="https://www.youtube.com/embed/k7KcO3pX7Z4" frameborder="0" allowfullscreen></iframe>', order: 51, featured: false },
  { title: "POS: How to Sell a Book/Item", slug: "pos-sell-book-item", description: "How to sell items using the POS.", thumbnail: "https://img.youtube.com/vi/bhByaH4g1zM/hqdefault.jpg", category: "Tutorials", audience: "Catholic In Person", resourceType: "Video", embedCode: '<iframe src="https://www.youtube.com/embed/bhByaH4g1zM" frameborder="0" allowfullscreen></iframe>', order: 52, featured: false },
  { title: "POS: Is the Price Ringing Up Correctly?", slug: "pos-price-check", description: "Verifying correct pricing on POS.", thumbnail: "https://img.youtube.com/vi/86bRZt2yl80/hqdefault.jpg", category: "Tutorials", audience: "Catholic In Person", resourceType: "Video", embedCode: '<iframe src="https://www.youtube.com/embed/86bRZt2yl80" frameborder="0" allowfullscreen></iframe>', order: 53, featured: false },
  { title: "No Receipts? Troubleshooting Receipt Paper Issues", slug: "no-receipts-troubleshooting", description: "Troubleshooting receipt paper issues on POS.", thumbnail: "/images/tip-sheet-thumb.png", fileUrl: "/documents/68e160d40ef1f7d8bd735326_ibf-pos-instructions.pdf", category: "Tutorials", audience: "Catholic In Person", resourceType: "PDF", order: 54, featured: false },

  // PUBLIC (16 total)
  { title: "Public Book Fair Administrator Operational Guide", slug: "public-book-fair-administrator-operational-guide", description: "Guide for public school book fair administrators.", thumbnail: "/images/operational-guide-thumb.png", fileUrl: "/documents/697cbfae2a935eb2468dde25_in-person-guide-public-1-30-26.pdf", category: "Public", audience: "Public In Person", resourceType: "PDF", order: 55, featured: true },
  { title: "Public School Book Fair Sneak Peek", slug: "public-school-book-fair-sneak-peek", description: "Preview of books for public school fairs.", thumbnail: "/images/thumb-neak-peek-public.png", fileUrl: "https://ignatius-book-fair.s3.us-east-2.amazonaws.com/public-school-bookfair-sneak-peek.pdf", category: "Public", audience: "Public In Person", resourceType: "PDF", order: 56, featured: false },
  { title: "Ignatius Book Fairs - Training Workshop/Public and Charter - Part 1", slug: "training-workshop-public-part-1", description: "Training workshop for public and charter schools - Part 1.", thumbnail: "/images/ibf-webinar-thumb.png", category: "Public", audience: "Public In Person", resourceType: "Video", embedCode: '<wistia-player media-id="1mtbd362de"></wistia-player>', order: 57, featured: false },
  { title: "Ignatius Book Fairs - Training Workshop/Public and Charter - Part 2", slug: "training-workshop-public-part-2", description: "Training workshop for public and charter schools - Part 2.", thumbnail: "/images/ibf-webinar-thumb.png", category: "Public", audience: "Public In Person", resourceType: "Video", embedCode: '<wistia-player media-id="f8h29r0uvk"></wistia-player>', order: 58, featured: false },
  { title: "Public Letter to Principal", slug: "public-letter-to-principal", description: "Letter template for public school principals.", thumbnail: "/images/principal-letter-thumb.png", fileUrl: "/documents/6972d0d876c9afbb4aa5270b_public-principals-letter.pdf", category: "Public", audience: "Public In Person", resourceType: "PDF", order: 59, featured: false },
  { title: "Public Social Media Tips", slug: "public-social-media-tips", description: "Social media tips for public school fairs.", thumbnail: "/images/social-media-v-thumb.png", fileUrl: "/documents/6972d0e19201ad56767b2c1e_public-social-media-tips.pdf", category: "Public", audience: "Public In Person", resourceType: "PDF", order: 60, featured: false },
  { title: "Public Blue Save the Date Interactive", slug: "public-blue-save-the-date", description: "Interactive blue save-the-date flyer.", thumbnail: "/images/thumb-public-blue-save-date.png", fileUrl: "/documents/68c2eecb28db63530c6b7ed3_Public%20full%20pg%20blue%20save%20the%20date%20interactive%20(1).pdf", category: "Public", audience: "Public In Person", resourceType: "PDF", order: 61, featured: false },
  { title: "Public Half Page Save Date Interactive", slug: "public-half-page-save-date", description: "Interactive half-page save-the-date.", thumbnail: "/images/thumb-public-half-page-save-date.png", fileUrl: "/documents/68c2eecbc1c8abecc85bbc7a_Public%20half%20save%20the%20dates%20interactive%20(1).pdf", category: "Public", audience: "Public In Person", resourceType: "PDF", order: 62, featured: false },
  { title: "Public Last Copy", slug: "public-last-copy", description: "Last copy tags for public school fairs.", thumbnail: "/images/thumb-lastcopy-inksaver.png", fileUrl: "/documents/689befc2592795e01e7ec14e_Public%20Last%20Copy%20Flyer.pdf", category: "Public", audience: "Public In Person", resourceType: "PDF", order: 63, featured: false },
  { title: "Public Social Media Post", slug: "public-social-media-post", description: "Social media post for public school fairs.", thumbnail: "/images/social-media-v-thumb.png", fileUrl: "/documents/68c2f636564f8d82274f2d2e_p-social-media-sneak-peek%201.png", category: "Public", audience: "Public In Person", resourceType: "Image", order: 64, featured: false },
  { title: "Public Student Wishlist", slug: "public-student-wishlist", description: "Wishlist for public school students.", thumbnail: "/images/student-wishlist-10-24-thumb.png", fileUrl: "/documents/68c2eecbeeb6694ff5ef4aee_Public%20School%20Student%20Wish%20List%20In%20person%20(1).pdf", category: "Public", audience: "Public In Person", resourceType: "PDF", order: 65, featured: false },
  { title: "Public Teacher Wishlist", slug: "public-teacher-wishlist", description: "Wishlist for public school teachers.", thumbnail: "/images/teacher-bookfair-sighlist-thumb.png", fileUrl: "/documents/68c2eecbcd5cf4cd71696a26_Public%20Teacher%20Wishlist%20%20(1).pdf", category: "Public", audience: "Public In Person", resourceType: "PDF", order: 66, featured: false },
  { title: "Public Virtual Teacher Wishlist", slug: "public-virtual-teacher-wishlist", description: "Virtual wishlist for public school teachers.", thumbnail: "/images/teacher-bookfair-sighlist-thumb.png", fileUrl: "/documents/68c2ed35b5c24a271366cd96_Public%20Virtual%20Wish%20List%20(1).pdf", category: "Public", audience: "Public In Person", resourceType: "PDF", order: 67, featured: false },
  { title: "Public Yellow Save the Date Interactive", slug: "public-yellow-save-the-date", description: "Interactive yellow save-the-date flyer.", thumbnail: "/images/thumb-public-yellow-save-date.png", fileUrl: "/documents/68c2ecd96c20decfeb2b5cd7_Public%20Yellow%20Save%20the%20Dates%20Interactive.pdf", category: "Public", audience: "Public In Person", resourceType: "PDF", order: 68, featured: false },
  { title: "Social - Feed the Imagination - public", slug: "social-feed-the-imagination-public", description: "Feed the Imagination social media graphic.", thumbnail: "/images/social-media-v-thumb.png", fileUrl: "/documents/68f7fd6519ff9663b28be54f_feed-imagination-social-ps.jpg", category: "Public", audience: "Public In Person", resourceType: "Image", order: 69, featured: false },
  { title: "Coming Soon Principal Letter", slug: "coming-soon-principal-letter", description: "Coming soon letter for principals.", thumbnail: "/images/principal-letter-thumb.png", fileUrl: "/documents/68a717e3c72cae04ce8237e1_IBF-coming-soon-letter.pdf", category: "Public", audience: "Public In Person", resourceType: "PDF", order: 70, featured: false },
];

async function main() {
  console.log('Clearing existing resources...');
  await prisma.resource.deleteMany({});

  console.log('Inserting new resources...');
  for (const resource of liveResources) {
    await prisma.resource.create({
      data: {
        ...resource,
        isActive: true,
      },
    });
  }

  console.log('Done! Inserted', liveResources.length, 'resources');

  // Verify counts
  const counts = await prisma.$queryRaw`
    SELECT category, COUNT(*) as count
    FROM "Resource"
    WHERE "isActive" = true
    GROUP BY category
    ORDER BY category
  `;
  console.log('\nResource counts by category:');
  console.log(counts);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
