// AUTO-GENERATED from BookFairPlanner calendar events (do not hand-edit; re-run
// /tmp/gen-checklist.cjs if the calendar changes). One checklist set per fair type.
export interface CalendarItem {
  id: string;
  label: string;
  phase: 'Pre-fair' | 'During the fair' | 'After the fair';
  daysFromFair: number;
  resourceSlug?: string;
}

export const CALENDAR_ITEMS_BY_TYPE: Record<string, CalendarItem[]> = {
  'catholic-in-person': [
    { id: 'workshop-1', label: 'Live Workshop Series - Part 1', phase: 'Pre-fair', daysFromFair: -90, resourceSlug: 'book-fair-administrator-operational-guide' },
    { id: 'admin-account', label: 'Create Your Admin Account', phase: 'Pre-fair', daysFromFair: -80, resourceSlug: 'creating-your-admin-account' },
    { id: 'workshop-2', label: 'Live Workshop Series - Part 2', phase: 'Pre-fair', daysFromFair: -60, resourceSlug: 'catholic-school-planning-checklist' },
    { id: 'week-6', label: 'Save the Date Announcement', phase: 'Pre-fair', daysFromFair: -42, resourceSlug: 'social-media-guide' },
    { id: 'week-5', label: 'Share Parent Account Video', phase: 'Pre-fair', daysFromFair: -35, resourceSlug: 'creating-a-parent-account' },
    { id: 'workshop-3', label: 'Live Workshop Series - Part 3', phase: 'Pre-fair', daysFromFair: -30 },
    { id: 'week-4', label: 'Second Save the Date & Sneak Peek', phase: 'Pre-fair', daysFromFair: -28, resourceSlug: 'bookfair-sneak-peek' },
    { id: 'week-3', label: 'Highlight Featured Titles', phase: 'Pre-fair', daysFromFair: -21, resourceSlug: 'bookfair-sneak-peek' },
    { id: 'wishlists', label: 'Distribute Wishlists', phase: 'Pre-fair', daysFromFair: -18, resourceSlug: 'student-wishlist' },
    { id: 'week-2', label: 'Principal Letter & Email Campaign', phase: 'Pre-fair', daysFromFair: -14, resourceSlug: 'principal-parent-letter-in-person' },
    { id: 'pulpit', label: 'Pulpit Announcement', phase: 'Pre-fair', daysFromFair: -10, resourceSlug: 'pulpit-announcement' },
    { id: 'book-delivery', label: 'Book Delivery Arrives', phase: 'Pre-fair', daysFromFair: -7, resourceSlug: 'table-signs' },
    { id: 'week-1', label: 'Sneak Peek & Final Reminders', phase: 'Pre-fair', daysFromFair: -7, resourceSlug: 'bookfair-sneak-peek' },
    { id: 'evening-before', label: 'Evening Before Fair - Social Post', phase: 'Pre-fair', daysFromFair: -1, resourceSlug: 'social-media-guide' },
    { id: 'day-1', label: 'Day 1 - Reading Challenge Kickoff', phase: 'During the fair', daysFromFair: 0, resourceSlug: 'reading-challenge-campaign' },
    { id: 'day-2', label: 'Day 2 - Shopping Hours Reminder', phase: 'During the fair', daysFromFair: 1, resourceSlug: 'social-media-guide' },
    { id: 'day-3', label: 'Day 3 - Reading Recommendations', phase: 'During the fair', daysFromFair: 2 },
    { id: 'day-4', label: 'Day 4 - Top Sellers', phase: 'During the fair', daysFromFair: 3 },
    { id: 'day-5', label: 'Day 5 - Reading Habits Post', phase: 'During the fair', daysFromFair: 4 },
    { id: 'day-6', label: 'Day 6 - Thank You Preview', phase: 'During the fair', daysFromFair: 5 },
    { id: 'day-7', label: 'Day 7 - Last Day Push', phase: 'During the fair', daysFromFair: 6 },
  ],
  'parish-in-person': [
    { id: 'workshop-1', label: 'Live Workshop Series - Part 1', phase: 'Pre-fair', daysFromFair: -90, resourceSlug: 'parish-book-fair-administrator-operational-guide' },
    { id: 'workshop-2', label: 'Live Workshop Series - Part 2', phase: 'Pre-fair', daysFromFair: -60 },
    { id: 'week-6', label: '6 Weeks Before — Save the Date', phase: 'Pre-fair', daysFromFair: -42, resourceSlug: 'social-media-guide' },
    { id: 'week-5', label: '5 Weeks Before — Share the Video', phase: 'Pre-fair', daysFromFair: -35, resourceSlug: 'what-makes-an-ignatius-book-fair-special' },
    { id: 'workshop-3', label: 'Live Workshop Series - Part 3', phase: 'Pre-fair', daysFromFair: -30 },
    { id: 'week-4', label: '4 Weeks Before — Social Media Reminder', phase: 'Pre-fair', daysFromFair: -28, resourceSlug: 'you-caption-it-social-media-post' },
    { id: 'week-3', label: '3 Weeks Before — Staff Picks & Recommendations', phase: 'Pre-fair', daysFromFair: -21, resourceSlug: 'bookfair-sneak-peek' },
    { id: 'week-2', label: '2 Weeks Before — Pastor Invitation', phase: 'Pre-fair', daysFromFair: -14, resourceSlug: 'pulpit-announcement' },
    { id: 'book-delivery', label: 'Book Delivery Arrives', phase: 'Pre-fair', daysFromFair: -7, resourceSlug: 'pos-device-instructions' },
    { id: 'week-1', label: '1 Week Before — Sneak Peek & Final Reminders', phase: 'Pre-fair', daysFromFair: -7, resourceSlug: 'bookfair-sneak-peek' },
    { id: 'evening-before', label: 'Evening Before Fair — Social Post', phase: 'Pre-fair', daysFromFair: -1, resourceSlug: 'you-caption-it-social-media-story' },
    { id: 'day-1', label: 'Day 1 — Reading Challenge Kickoff', phase: 'During the fair', daysFromFair: 0, resourceSlug: 'reading-challenge-campaign' },
    { id: 'day-2', label: 'Day 2 — Shopping Hours Reminder', phase: 'During the fair', daysFromFair: 1, resourceSlug: 'social-media-guide' },
    { id: 'day-3', label: 'Day 3 — Reading Recommendations', phase: 'During the fair', daysFromFair: 2 },
    { id: 'day-4', label: 'Day 4 — Top Sellers', phase: 'During the fair', daysFromFair: 3 },
    { id: 'day-5', label: 'Day 5 — Foster a Love of Reading', phase: 'During the fair', daysFromFair: 4 },
    { id: 'day-6', label: 'Day 6 — Thank You & Recommendations', phase: 'During the fair', daysFromFair: 5 },
    { id: 'day-7', label: 'Day 7 — Last Day!', phase: 'During the fair', daysFromFair: 6 },
  ],
  'public-in-person': [
    { id: 'workshop-1', label: 'Training Workshop - Part 1', phase: 'Pre-fair', daysFromFair: -90, resourceSlug: 'public-book-fair-administrator-operational-guide' },
    { id: 'workshop-2', label: 'Training Workshop - Part 2', phase: 'Pre-fair', daysFromFair: -60, resourceSlug: 'training-workshop-public-part-2' },
    { id: 'week-6', label: '6 Weeks Before — Save the Date', phase: 'Pre-fair', daysFromFair: -42, resourceSlug: 'public-blue-save-the-date' },
    { id: 'week-5', label: '5 Weeks Before — Share the Video', phase: 'Pre-fair', daysFromFair: -35, resourceSlug: 'what-makes-an-ignatius-book-fair-special' },
    { id: 'week-4', label: '4 Weeks Before — Social Media Reminder', phase: 'Pre-fair', daysFromFair: -28, resourceSlug: 'public-yellow-save-the-date' },
    { id: 'week-3', label: '3 Weeks Before — Staff Picks & Recommendations', phase: 'Pre-fair', daysFromFair: -21, resourceSlug: 'public-school-book-fair-sneak-peek' },
    { id: 'wishlists', label: 'Distribute Wishlists', phase: 'Pre-fair', daysFromFair: -18, resourceSlug: 'public-student-wishlist' },
    { id: 'week-2', label: '2 Weeks Before — Principal Letter', phase: 'Pre-fair', daysFromFair: -14, resourceSlug: 'public-letter-to-principal' },
    { id: 'book-delivery', label: 'Book Delivery Arrives', phase: 'Pre-fair', daysFromFair: -7, resourceSlug: 'pos-device-instructions' },
    { id: 'week-1', label: '1 Week Before — Sneak Peek & Final Reminders', phase: 'Pre-fair', daysFromFair: -7, resourceSlug: 'public-school-book-fair-sneak-peek' },
    { id: 'evening-before', label: 'Evening Before Fair — Social Post', phase: 'Pre-fair', daysFromFair: -1, resourceSlug: 'social-feed-the-imagination-public' },
    { id: 'day-1', label: 'Day 1 — Reading Challenge Kickoff', phase: 'During the fair', daysFromFair: 0, resourceSlug: 'pos-device-instructions' },
    { id: 'day-2', label: 'Day 2 — Shopping Hours Reminder', phase: 'During the fair', daysFromFair: 1, resourceSlug: 'public-social-media-tips' },
    { id: 'day-3', label: 'Day 3 — Reading Recommendations', phase: 'During the fair', daysFromFair: 2 },
    { id: 'day-4', label: 'Day 4 — Top Sellers', phase: 'During the fair', daysFromFair: 3 },
    { id: 'day-5', label: 'Day 5 — Foster a Love of Reading', phase: 'During the fair', daysFromFair: 4 },
    { id: 'day-6', label: 'Day 6 — Thank You & Recommendations', phase: 'During the fair', daysFromFair: 5 },
    { id: 'day-7', label: 'Day 7 — Last Day!', phase: 'During the fair', daysFromFair: 6 },
  ],
  'catholic-virtual': [
    { id: 'week-7', label: '7 Weeks Before — Set Up & Invite Teachers', phase: 'Pre-fair', daysFromFair: -49, resourceSlug: 'virtual-book-fair-operational-guide' },
    { id: 'week-6', label: '6 Weeks Before — Save the Date', phase: 'Pre-fair', daysFromFair: -42, resourceSlug: 'you-caption-it-social-media-post' },
    { id: 'week-5', label: '5 Weeks Before — Share the Video', phase: 'Pre-fair', daysFromFair: -35, resourceSlug: 'what-makes-an-ignatius-book-fair-special' },
    { id: 'week-4', label: '4 Weeks Before — Social Media Reminder', phase: 'Pre-fair', daysFromFair: -28, resourceSlug: 'virtual-fillable-social-media-post-1' },
    { id: 'week-3', label: '3 Weeks Before — Staff Picks & Recommendations', phase: 'Pre-fair', daysFromFair: -21, resourceSlug: 'digital-catalog' },
    { id: 'week-2', label: '2 Weeks Before — Principal/Pastor Letter', phase: 'Pre-fair', daysFromFair: -14, resourceSlug: 'principal-parent-letter-virtual' },
    { id: 'week-1', label: '1 Week Before — Backpack Flyer', phase: 'Pre-fair', daysFromFair: -7, resourceSlug: 'virtual-backpack-flyer-2' },
    { id: 'evening-before', label: 'Evening Before Fair', phase: 'Pre-fair', daysFromFair: -1, resourceSlug: 'virtual-you-caption-it-2' },
    { id: 'day-1', label: 'Day 1 — Fair Opens! Reading Challenge', phase: 'During the fair', daysFromFair: 0, resourceSlug: 'reading-challenge-campaign' },
    { id: 'day-2', label: 'Day 2 — Social Media Push', phase: 'During the fair', daysFromFair: 1, resourceSlug: 'you-caption-it-social-media-print-ad-1' },
    { id: 'day-3', label: 'Day 3 — Reading Recommendations', phase: 'During the fair', daysFromFair: 2, resourceSlug: 'digital-catalog' },
    { id: 'day-4', label: 'Day 4 — Staff Top Picks', phase: 'During the fair', daysFromFair: 3, resourceSlug: 'you-caption-it-social-media-post' },
    { id: 'day-5', label: 'Day 5 — Foster a Love of Reading', phase: 'During the fair', daysFromFair: 4 },
    { id: 'day-6', label: 'Day 6 — Thank You & Recommendations', phase: 'During the fair', daysFromFair: 5 },
    { id: 'day-7', label: 'Day 7 — Last Day!', phase: 'During the fair', daysFromFair: 6, resourceSlug: 'you-caption-it-social-media-post' },
  ],
};
